name: template

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v2
    with:
      flutter_channel: stable
      flutter_version: "3.41.6"
      min_coverage: 0
      setup: "flutter gen-l10n && dart run build_runner build --delete-conflicting-outputs"
